CREATE DATABASE IF NOT EXISTS adoc;
CREATE DATABASE IF NOT EXISTS test;

CREATE USER IF NOT EXISTS 'adoc'@'%' IDENTIFIED BY 'adoc';
GRANT ALL PRIVILEGES ON adoc.* TO 'adoc'@'%';
GRANT ALL PRIVILEGES ON test.* TO 'adoc'@'%';

FLUSH PRIVILEGES;