services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    hostname: mysql-container.docker
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adoc
      MYSQL_DATABASE: adoc
      MYSQL_USER: adoc
      MYSQL_PASSWORD: adoc
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create_multi_db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    hostname: mongodb-container.docker
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adoc
      MONGO_INITDB_ROOT_PASSWORD: adoc
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - mongodb
    container_name: adoc-backend
    environment:
      DB_URL: mysql+pymysql://adoc:adoc@mysql-container.docker:3306/adoc
      MONGODB_URI: mongodb://adoc:adoc@mongodb-container.docker:27017/adoc?authSource=admin
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

volumes:
  mysql_data: {}
  mongo_data: {}
