services:
  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: backend
    container_name: backend
    environment:
      DB_URL: postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

  postgres:
    image: postgres:15
    container_name: local_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data\

volumes:
  postgre_data: {}
