"""add user address

Revision ID: 02e756938035
Revises: ac3e67b04198
Create Date: 2025-01-16 22:25:06.444738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e756938035'
down_revision: Union[str, None] = 'ac3e67b04198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'address', sa.String(), nullable=False, comment='사용자 주소', server_default='test'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
