"""Initial migration

Revision ID: 09622e805dfe
Revises: 
Create Date: 2025-01-21 11:02:17.676347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09622e805dfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='사용자 이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='사용자 비밀번호'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='레코드가 생성된 시간 in UTC'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='레코드가 마지막으로 업데이트된 시간 in UTC'),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 정보'
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
