"""Add refresh token model

Revision ID: 8b8cfed74507
Revises: 09622e805dfe
Create Date: 2025-01-21 11:42:27.969724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8cfed74507'
down_revision: Union[str, None] = '09622e805dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user pk'),
    sa.Column('refresh_token', sa.String(length=255), nullable=False, comment='사용자 refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='레코드가 생성된 시간 in UTC'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='레코드가 생성된 시간 in UTC'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='레코드가 마지막으로 업데이트된 시간 in UTC'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 refresh token 정보'
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_updated_at'), 'refresh_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_updated_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
