"""refresh token nullable true

Revision ID: 91863a8d3f77
Revises: a336e3b3603f
Create Date: 2025-01-22 21:00:38.732656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91863a8d3f77'
down_revision: Union[str, None] = 'a336e3b3603f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'refresh_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='사용자 refresh token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'refresh_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='사용자 refresh token')
    # ### end Alembic commands ###
