"""init

Revision ID: b7e0f17e3c0b
Revises: 
Create Date: 2025-01-21 20:54:46.255391

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7e0f17e3c0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='사용자 이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='사용자 비밀번호'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='레코드가 생성된 시간 in UTC'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='레코드가 마지막으로 업데이트된 시간 in UTC'),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 정보'
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user pk'),
    sa.Column('refresh_token', sa.String(length=255), nullable=False, comment='사용자 refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='레코드가 생성된 시간 in UTC'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='레코드가 생성된 시간 in UTC'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='레코드가 마지막으로 업데이트된 시간 in UTC'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 refresh token 정보'
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_updated_at'), 'refresh_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_updated_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
