from enum import StrEnum


class BoardAction(StrEnum):
    CREATE_FAIL = "CREATE FAIL"
    NO_USER_FOUND = "NO USER FOUND"
    INVALID_PASSWORD = "INVALID PASSWORD"
    NO_POST_FOUND = "NO POST FOUND"
    INVALID_ID_FORMAT = "INVALID ID FORMAT"
