from enum import StrEnum


class TokenType(StrEnum):

    ACCESS = "ACCESS"
    REFRESH = "REFRESH"

class TokenAuth(StrEnum):

    REFRESH_TOKEN_EXPIRED = "REFRESH TOKEN EXPIRED"
    ACCESS_TOKEN_EXPIRED = "ACCESS TOKEN EXPIRED"
    INVALID_TOKEN = "INVALID TOKEN"
    INVALID_AUTH_SCHEME = "INVALID AUTH SCHEME"
